esphome:
  name: m5stack-core2

esp32:
  board: m5stack-core-esp32
  framework:
    type: esp-idf

  # Use this to hardlink the component if it is not discovered
  # includes:
  #  - /config/custom_components/axp192/axp192.h

wifi:
  ssid: "SSID"
  password: "PASSPHRASE"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "XXX"
    password: "XXX"

substitutions:
  devicename: ${devicename}
  upper_devicename: ${upper_devicename}

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:

# Setup external axp192 component
external_components:
  - source: github://BalazsGyarmati/esphome-axp192
    components: [axp192]

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO38

i2c:
    - id: i2c_bus
      sda: GPIO21
      scl: GPIO22
      scan: True

# AXP192 power management - must be present to initialize TFT power on
sensor:
  - platform: axp192
    model: M5CORE2
    address: 0x34
    i2c_id: i2c_bus
    update_interval: 60s
	  brightness: 75%
    battery_level:
      name: ${upper_devicename} Battery Level
      id: batterylevel

  - platform: wifi_signal
    name: ${upper_devicename} WiFi Signal
    id: wifi_dbm
  - platform: uptime
    name: ${upper_devicename} Uptime

font:
  - file: 'fonts/arial.ttf'
    id: font1
    size: 8

display:
  - platform: ili9341
    # 320x240
    model: M5STACK
    cs_pin: 5
    dc_pin: 15
    lambda: |-
      it.line(20, 20, 200, 200);
